# fly.toml app configuration file generated for halo-backend-solitary-smoke-5582 on 2025-10-12T14:17:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'halo-backend-solitary-smoke-5582'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
